#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mailpit"
name = "Mailpit"
description.en = "Modern SMTP testing server with web UI to inspect captured emails"
description.fr = "Serveur SMTP de test moderne avec interface web pour inspecter les emails"

version = "1.31.4~ynh1"

maintainers = ["patou"]

[upstream]
license = "MIT"
website = "https://mailpit.axllent.org"
admindoc = "https://mailpit.axllent.org/docs/"
code = "https://github.com/axllent/mailpit"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "i386", "armhf", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "80M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mailpit"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]

    [resources.sources.main]
    format = "tar.gz"
    extract = true
    in_subdir = false

        [resources.sources.main.amd64]
        url = "https://github.com/axllent/mailpit/releases/download/v1.31.4/mailpit-linux-amd64.tar.gz"
        sha256 = "30942c4605c2ca8b9f759b1bb4e3ab6a12bdfdf66e5c94644ec2c75ac41e88e7"

        [resources.sources.main.i386]
        url = "https://github.com/axllent/mailpit/releases/download/v1.31.4/mailpit-linux-386.tar.gz"
        sha256 = "83638060c3caafd50829610e94a371cca77468cd7c149eead828c5c8297a13b5"

        [resources.sources.main.armhf]
        url = "https://github.com/axllent/mailpit/releases/download/v1.31.4/mailpit-linux-arm.tar.gz"
        sha256 = "f000853dcdb2747239bffd1343c2e85745751d15324d20d550fb612d5b48363e"

        [resources.sources.main.arm64]
        url = "https://github.com/axllent/mailpit/releases/download/v1.31.4/mailpit-linux-arm64.tar.gz"
        sha256 = "010a346a8b9d454f6fa22d4fd2dbd5bf5eb7104688412b9c130d0ba33a3579c4"

        [resources.sources.main.autoupdate]
        strategy = "latest_github_release"
        asset.amd64 = "mailpit-linux-amd64.tar.gz"
        asset.i386 = "mailpit-linux-386.tar.gz"
        asset.armhf = "mailpit-linux-arm.tar.gz"
        asset.arm64 = "mailpit-linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8025
    smtp.default = 1025
    smtp.exposed = "TCP"
