#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mailpit"
name = "Mailpit"
description.en = "Modern SMTP testing server with web UI to inspect captured emails"
description.fr = "Serveur SMTP de test moderne avec interface web pour inspecter les emails"

version = "1.30.7~ynh1"

maintainers = ["patou"]

[upstream]
license = "MIT"
website = "https://mailpit.axllent.org"
admindoc = "https://mailpit.axllent.org/docs/"
code = "https://github.com/axllent/mailpit"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "i386", "armhf", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "80M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mailpit"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]

    [resources.sources.main]
    format = "tar.gz"
    extract = true
    in_subdir = false

        [resources.sources.main.amd64]
        url = "https://github.com/axllent/mailpit/releases/download/v1.30.7/mailpit-linux-amd64.tar.gz"
        sha256 = "a35c053509441b95fb96da6479b3a26b3eb309e223232aced28255c011d29efc"

        [resources.sources.main.i386]
        url = "https://github.com/axllent/mailpit/releases/download/v1.30.7/mailpit-linux-386.tar.gz"
        sha256 = "356fc38158623446142f8939c627aba6ee03c9d6d61ea3c3e511d0cc59f11402"

        [resources.sources.main.armhf]
        url = "https://github.com/axllent/mailpit/releases/download/v1.30.7/mailpit-linux-arm.tar.gz"
        sha256 = "9b18bed969e5088dc7c4e89d2e82a9ce0905fa49ceb6831e156652b3ac571dbc"

        [resources.sources.main.arm64]
        url = "https://github.com/axllent/mailpit/releases/download/v1.30.7/mailpit-linux-arm64.tar.gz"
        sha256 = "12c736a73d122c55d3531ac2fc92cad96dbde283af661b6701fe32892bd438c5"

        [resources.sources.main.autoupdate]
        strategy = "latest_github_release"
        asset.amd64 = "mailpit-linux-amd64.tar.gz"
        asset.i386 = "mailpit-linux-386.tar.gz"
        asset.armhf = "mailpit-linux-arm.tar.gz"
        asset.arm64 = "mailpit-linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8025
    smtp.default = 1025
    smtp.exposed = "TCP"
