#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mailpit"
name = "Mailpit"
description.en = "Modern SMTP testing server with web UI to inspect captured emails"
description.fr = "Serveur SMTP de test moderne avec interface web pour inspecter les emails"

version = "1.30.6~ynh1"

maintainers = ["patou"]

[upstream]
license = "MIT"
website = "https://mailpit.axllent.org"
admindoc = "https://mailpit.axllent.org/docs/"
code = "https://github.com/axllent/mailpit"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "i386", "armhf", "arm64"]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "80M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mailpit"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]

    [resources.sources.main]
    format = "tar.gz"
    extract = true
    in_subdir = false

        [resources.sources.main.amd64]
        url = "https://github.com/axllent/mailpit/releases/download/v1.30.6/mailpit-linux-amd64.tar.gz"
        sha256 = "00f7570bf47c9683944f6189379ce4b7d4974b1c9cd911f93c55d4ad945bf3d2"

        [resources.sources.main.i386]
        url = "https://github.com/axllent/mailpit/releases/download/v1.30.6/mailpit-linux-386.tar.gz"
        sha256 = "8b90d7eb74dac237e1b5097d8cf85a4633ca5670cd9a16c59273351b2897c044"

        [resources.sources.main.armhf]
        url = "https://github.com/axllent/mailpit/releases/download/v1.30.6/mailpit-linux-arm.tar.gz"
        sha256 = "601fa9e14e8ee2bb30ca2e78f9743704bf9b8b436dba87e55abd816d9f8324f3"

        [resources.sources.main.arm64]
        url = "https://github.com/axllent/mailpit/releases/download/v1.30.6/mailpit-linux-arm64.tar.gz"
        sha256 = "80ecee9cd8d28c4eb908dc27c5ce4505a708b4d5ad4602eac0c6540a8df53f53"

        [resources.sources.main.autoupdate]
        strategy = "latest_github_release"
        asset.amd64 = "mailpit-linux-amd64.tar.gz"
        asset.i386 = "mailpit-linux-386.tar.gz"
        asset.armhf = "mailpit-linux-arm.tar.gz"
        asset.arm64 = "mailpit-linux-arm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8025
    smtp.default = 1025
    smtp.exposed = "TCP"
